version: '3'
services:
  node:
    build:
      context: .
    command: bash -c "yarn install && yarn run parcel --hmr-port 1235 --hmr-hostname localhost src/index.html"
    volumes:
      - '.:/myapp'
    ports:
      - '4001:1234'
      - '1235:1235'
    tty: true
    stdin_open: true
